"""Docked AI direction, range feedback, and shared timeline audition."""
from .rig_layout_ui import MAP_SCRIPT

STYLE = r'''
.inspector-tabs{display:flex;position:sticky;top:0;z-index:5;background:var(--panel);gap:4px;padding:0 0 7px;border-bottom:1px solid var(--line)}.inspector-tabs button{flex:1;min-height:29px;padding:5px}.inspector-tabs button[aria-selected=true]{border-color:var(--accent);color:var(--accent)}aside.inspector>h2{display:none}.inspector.director-mode>#form,.inspector.director-mode>#noClip{display:none!important}#aiPanel{padding:7px 0}#aiPanel .hint{white-space:pre-wrap;font-size:11px;line-height:1.5}#aiPanel label{margin:8px 0}#aiPanel input,#aiPanel select{min-height:27px;padding:5px}#aiPanel textarea{min-height:90px;resize:vertical;font:12px system-ui}#aiPanel .row{gap:4px;margin:8px 0}#aiPanel button{font-size:11px;min-height:27px;padding:5px}#aiPanel details{margin:10px 0}#aiProvider{font-size:10px;color:var(--muted);margin:4px 0 8px}#aiStage{padding:7px;background:#273123;border-left:2px solid var(--accent);font-size:11px;line-height:1.5}#aiStage.busy:before{content:'';display:inline-block;width:9px;height:9px;border:2px solid #607348;border-top-color:var(--accent);border-radius:50%;animation:spin 1s linear infinite;margin-right:6px}#aiSummary{font-size:12px;line-height:1.5;white-space:pre-wrap}.conversation{font-size:11px;line-height:1.5;max-height:240px;overflow:auto}.conversation p{border-bottom:1px solid var(--line);padding-bottom:7px}.proposal-list button{display:block;width:100%;text-align:left;margin:3px 0}#aiClips{max-height:170px;overflow:auto}#aiReview{padding:4px 6px;border-bottom:1px solid var(--line);background:#273322;font-size:11px;margin:0;gap:6px}#aiReview label{margin:0;font-size:11px}#aiReview button{min-height:24px;padding:3px 6px;font-size:11px}#aiReviewStatus{flex:1;color:var(--accent)}#aiCanvas{display:none;flex:1 1 0;min-height:120px;height:0;width:100%;background:#111711}.workspace.show-rig-map #rig{display:none}.workspace.show-rig-map #aiCanvas{display:block}.ai-entry{display:block;width:100%;margin-top:10px;padding:7px;text-align:center;border:1px solid var(--line);border-radius:4px;text-decoration:none;color:var(--text)}#timeSelectionLabel{color:var(--accent)}#timeline.selecting{cursor:col-resize}.selection-tools{display:flex;gap:5px;align-items:center;margin:0;padding:3px 6px;border-bottom:1px solid var(--line);font-size:10px;color:var(--muted)}.selection-tools button{font-size:10px;min-height:23px;padding:3px 6px}.selection-tools span{flex:1}.feedback-buttons{display:flex;gap:4px;flex-wrap:wrap}#aiNotice{min-height:15px}#aiPanel .pair{gap:7px}
@media(max-height:700px){#aiCanvas{min-height:80px}.selection-tools{padding:2px 5px}.selection-tools button{min-height:21px}}
'''
HTML = r'''
<section id="aiPanel" hidden aria-label="AI director"><div id="aiProvider"></div><div id="aiStage" role="status">Select a passage on the waveform, or arrange the whole track.</div><label>Work on<select id="aiScope"><option value="track">Whole track</option><option value="selection">Timeline selection</option><option value="here">Around playhead</option><option value="region">Loop region</option><option value="clip">Selected clip</option><option value="proposal" id="aiProposalScope" disabled>Previous proposal region</option></select></label><div class="pair"><label>From (seconds)<input id="aiStart" type="number" min="0" step=".001"></label><label>To (seconds)<input id="aiEnd" type="number" min="0" step=".001"></label></div><p id="aiRange" class="hint"></p><div class="feedback-buttons"><button id="feedbackQuiet">Less busy</button><button id="feedbackImpact">Bigger impact</button><button id="feedbackUp">Move upward</button></div><label>Your direction<textarea id="aiInstruction" rows="4" maxlength="4000" placeholder="Keep these colours, but hold back here and sweep upward into the drop."></textarea></label><div class="row"><button id="generateAI" class="primary">Suggest lighting</button><button id="reviseAI" disabled>Revise draft</button><button id="cancelAI" disabled>Discard draft</button></div><p id="aiNotice" class="hint" role="status"></p><p id="aiSummary"></p><div id="aiClips" class="proposal-list"></div><details><summary>Conversation</summary><div id="aiConversation" class="conversation"></div></details><details><summary>Musical preferences</summary><label>Used for every suggestion<textarea id="aiPreferences" maxlength="4000" rows="5"></textarea></label><button id="saveAIPreferences">Save preferences</button></details><p class="hint">Suggest sends the selected audio, up to 8 seconds of surrounding context, musical analysis and your rig map to Google Gemini. Send to LEDs follows the A/B selection, including unapplied drafts. Apply saves the draft. Locked passages stay protected.</p></section>
<div id="aiReview" class="row" hidden><span id="aiReviewStatus">Draft lighting</span><label><input id="aiAudition" type="checkbox" checked> B · Proposed</label><button id="aiCompare">Hear / see A</button><button id="applyAI" class="primary" disabled>Apply draft</button></div>
<canvas id="aiCanvas" aria-label="Physical rig preview"></canvas>
'''
SCRIPT = MAP_SCRIPT + r'''
let aiConfig=null,aiJob=null,aiTrack=null,aiRange=[0,0],aiBusy=false,aiPollBusy=false,aiMutating=false,aiEpoch=0,aiColours={},lastDirectorRoute=null;
const aiAudio=audio, workspace=document.querySelector('.workspace');
$('inspector').append($('aiPanel'));
$('timeline').before($('aiReview'));
$('rig').after($('aiCanvas'));
const tabs=document.createElement('div');tabs.className='inspector-tabs';tabs.setAttribute('role','tablist');
tabs.innerHTML='<button id="clipTab" role="tab" aria-selected="true">Clip inspector</button><button id="directorTab" role="tab" aria-selected="false">AI director</button>';
$('inspector').prepend(tabs);
function directorShown(){return !$('aiPanel').hidden;}
function aiReady(){return aiJob?.status==='ready'&&aiJob.track===tid&&aiJob.revision===state.revision&&aiJob.settings_revision===aiConfig?.revision;}
function proposedView(){return aiReady()&&$('aiAudition').checked;}
window.directorVisibleTrack=()=>proposedView()?aiJob.project.tracks.find(t=>t.id===tid):null;
window.directorPreviewPath=()=>aiMutating?false:proposedView()?'ai/preview?id='+encodeURIComponent(aiJob.id):null;
window.directorFrame=frame=>{aiColours=frame;if(workspace.classList.contains('show-rig-map'))drawPhysical('aiCanvas',aiConfig?.layout||{},frame);};
window.directorPreviewFailed=async message=>{$('aiAudition').checked=false;aiNotice(message,true);aiButtons();try{aiConfig=await request('ai/config');aiButtons();}catch{}drawTimeline();};
window.directorIsProposed=proposedView;
window.directorTransportProposal=()=>!aiMutating&&proposedView()?aiJob.id:null;
function aiNotice(value,error=false){$('aiNotice').textContent=value;$('aiNotice').classList.toggle('error',error);}
async function suspendAIPreview(){aiMutating=true;aiEpoch++;while(frameBusy)await new Promise(resolve=>setTimeout(resolve,20));}
function showDirector(show){$('aiPanel').hidden=!show;$('inspector').classList.toggle('director-mode',show);$('clipTab').setAttribute('aria-selected',String(!show));$('directorTab').setAttribute('aria-selected',String(show));workspace.classList.toggle('show-rig-map',show||proposedView());if(show&&innerWidth<=900)$('desk').classList.add('show-inspector');drawTimeline();drawAI();}
$('clipTab').onclick=()=>{if(proposedView()){$('aiAudition').checked=false;compareAI();}showDirector(false);};window.directorInspectClip=()=>showDirector(false);$('directorTab').onclick=()=>openAI();
function aroundPlayhead(){const t=audio.currentTime||0,duration=track()?.duration||0,beats=analysis.beats||[];if(beats.length>4){const i=beats.reduce((best,b,j)=>Math.abs(b-t)<Math.abs(beats[best]-t)?j:best,0);return [Math.max(0,Math.min(t,beats[Math.max(0,i-4)])),Math.min(duration,Math.max(t+.05,beats[Math.min(beats.length-1,i+4)]))];}return [Math.max(0,t-4),Math.min(duration,t+4)];}
function chosenAIRange(){const tr=track();if(!tr)throw Error('Import and select a track first');const scope=$('aiScope').value;const range=scope==='selection'?timeSelection:scope==='here'?aroundPlayhead():scope==='proposal'?aiJob?.range:scope==='clip'?(clip()?[clip().start,clip().end]:null):scope==='region'?[+$('loopIn').value,+$('loopOut').value]:[0,tr.duration];if(!range||!range.every(Number.isFinite)||range[0]<0||range[1]>tr.duration||range[1]-range[0]<.05)throw Error('Drag a passage on the waveform or enter a valid start and end');return [...range];}
function showAIRange(){try{aiRange=chosenAIRange();$('aiRange').textContent=format(aiRange[0])+' – '+format(aiRange[1]);$('aiStart').value=Number(aiRange[0].toFixed(3));$('aiEnd').value=Number(aiRange[1].toFixed(3));}catch(e){$('aiRange').textContent=e.message;}}
window.directorSelectionChanged=()=>{if(timeSelection)$('aiScope').value='selection';else if($('aiScope').value==='selection')$('aiScope').value='here';showAIRange();};
for(const id of ['aiStart','aiEnd'])$(id).onchange=()=>{const range=[+$('aiStart').value,+$('aiEnd').value];if(!range.every(Number.isFinite)||range[0]<0||range[1]>(track()?.duration||0)||range[1]-range[0]<.05)return aiNotice('Choose a valid start and end inside the track',true);setTimeSelection(range);aiNotice('');};
$('aiScope').onchange=showAIRange;
function drawAI(){if(workspace.classList.contains('show-rig-map'))drawPhysical('aiCanvas',aiConfig?.layout||{},aiColours);}
function aiButtons(){const ready=aiReady(),parent=aiJob&&aiJob.track===tid&&['ready','applied'].includes(aiJob.status)&&(aiJob.revision===state.revision||aiJob.applied_revision===state.revision);$('generateAI').disabled=aiBusy||!aiConfig?.configured||!state.ready[tid];$('reviseAI').disabled=aiBusy||!parent;$('cancelAI').disabled=!aiJob||['cancelled','applied'].includes(aiJob.status);$('applyAI').disabled=!ready||aiBusy;$('aiScope').disabled=aiBusy;$('saveAIPreferences').disabled=aiBusy;$('aiStage').classList.toggle('busy',aiBusy);$('aiReview').hidden=!aiJob||aiJob.track!==tid||aiJob.status!=='ready';$('aiReviewStatus').textContent=ready?(proposedView()?($('output').checked?'B · Draft lighting · live':'B · Draft lighting · preview'):'A · Saved lighting'):'Draft is stale — suggest again';$('aiCompare').textContent=proposedView()?'Hear / see A':'Hear / see B';$('output').disabled=false;for(const id of ['duplicate','delete','savePreset','loopClip'])$(id).disabled=proposedView()||!clip();for(const id of ['addGuided','addLED'])$(id).disabled=proposedView()||!track();const route=window.directorTransportProposal();if(route!==lastDirectorRoute){lastDirectorRoute=route;sync();}$('outputStatus').textContent=$('output').checked?'● Sending to LEDs':'Preview only';$('outputStatus').classList.toggle('live',$('output').checked);workspace.classList.toggle('show-rig-map',directorShown()||proposedView());}
window.directorStateChanged=()=>{aiButtons();if(aiJob?.status==='ready'&&aiJob.track===tid&&!aiReady())aiNotice('The saved arrangement changed. Suggest again to use the latest edits.',true);};
async function openAI(scope){try{if(!track())throw Error('Import and select a track first');aiConfig=await request('ai/config');if(aiTrack!==tid&&!aiBusy){aiJob=null;$('aiConversation').replaceChildren();$('aiSummary').textContent='';$('aiClips').replaceChildren();$('aiStage').textContent='Select a passage or arrange the whole track.';}if(!aiBusy)aiTrack=tid;if(!aiJob&&aiConfig.job?.track===tid){aiJob=await request('ai/job?id='+encodeURIComponent(aiConfig.job.id));$('aiProposalScope').disabled=false;$('aiScope').value='proposal';renderAIJob();}$('aiPreferences').value=aiConfig.preferences;$('aiProvider').textContent=aiConfig.configured?'Gemini · '+aiConfig.model:'Set GEMINI_API_KEY on the server and restart Rigby.';if(typeof scope==='string')$('aiScope').value=scope;else if(timeSelection)$('aiScope').value='selection';showAIRange();aiNotice('');showDirector(true);aiButtons();}catch(e){message(e.message,true);}}
window.directorTrackChanged=()=>{if(directorShown()&&!aiBusy)openAI();};
window.directorOpenSelection=()=>openAI('selection');
window.directorChangeHere=async()=>{setTimeSelection(aroundPlayhead());await openAI('selection');$('aiInstruction').focus();};
for(const [id,instruction] of [['feedbackQuiet','Make this passage less busy. Reduce movement and colour churn while preserving its musical character.'],['feedbackImpact','Make this passage hit harder, with a clear contrast against the preceding quiet section.'],['feedbackUp','Keep the musical timing, but move the light upward across the physical rig.']])$(id).onclick=()=>{if(!timeSelection)setTimeSelection(aroundPlayhead());$('aiScope').value='selection';showAIRange();$('aiInstruction').value=instruction;$('aiInstruction').focus();};
$('saveAIPreferences').onclick=async()=>{try{aiConfig=await request('ai/settings',{layout:aiConfig.layout,preferences:$('aiPreferences').value,revision:aiConfig.revision});aiNotice('Preferences saved. Suggest again to use them.');}catch(e){aiNotice(e.message,true);}};
async function generateAI(revise){try{if(inspectorDrafts.size)throw Error('Apply or discard inspector changes before requesting a suggestion');if(aiBusy)throw Error('Wait for the current suggestion to finish');aiRange=chosenAIRange();aiTrack=tid;const instructionInput=$('aiInstruction').value,instruction=instructionInput.trim()||'Suggest a musical lighting arrangement for this passage.';aiBusy=true;aiButtons();aiNotice('');await suspendAIPreview();if($('aiPreferences').value!==aiConfig.preferences)aiConfig=await request('ai/settings',{layout:aiConfig.layout,preferences:$('aiPreferences').value,revision:aiConfig.revision});const job=await request('ai/generate',{track:tid,revision:state.revision,start:aiRange[0],end:aiRange[1],instruction,parent:revise?aiJob.id:undefined});aiJob=job;const entry=document.createElement('p');entry.textContent='You: '+instruction;$('aiConversation').append(entry);if($('aiInstruction').value===instructionInput)$('aiInstruction').value='';$('aiSummary').textContent='';$('aiClips').replaceChildren();$('aiStage').textContent=job.stage;}catch(e){aiBusy=false;aiNotice(e.message,true);}finally{aiMutating=false;}aiButtons();drawTimeline();}
$('generateAI').onclick=()=>generateAI(aiReady());$('reviseAI').onclick=()=>generateAI(true);
$('cancelAI').onclick=async()=>{try{await suspendAIPreview();if(aiJob){aiJob=await request('ai/cancel',{id:aiJob.id});aiBusy=false;$('aiStage').textContent='Draft discarded';$('aiSummary').textContent='';$('aiClips').replaceChildren();}}catch(e){aiNotice(e.message,true);}finally{aiMutating=false;aiButtons();drawTimeline();preview();}};
$('applyAI').onclick=()=>enqueue(async()=>{if(!aiReady())return;if(inspectorDrafts.size)return aiNotice('Apply or discard inspector changes before applying the draft',true);await suspendAIPreview();try{const before=clone(state.project);state=await request('ai/apply',{id:aiJob.id});undo.push(before);if(undo.length>50)undo.shift();redo=[];aiJob.status='applied';aiJob.applied_revision=state.revision;cid=null;drawAll();$('aiStage').textContent='Applied — clips are ready to edit';aiNotice('Saved. Undo restores the previous arrangement.');message('AI arrangement applied');}catch(e){aiNotice(e.message,true);throw e;}finally{aiMutating=false;aiButtons();drawTimeline();preview();}});
async function compareAI(){await suspendAIPreview();aiMutating=false;aiButtons();drawTimeline();preview();}
$('aiAudition').onchange=compareAI;$('aiCompare').onclick=()=>{$('aiAudition').checked=!$('aiAudition').checked;compareAI();};
function renderAIJob(){$('aiStage').textContent=aiJob.stage;aiBusy=aiJob.status==='running';if(aiJob.status==='error')aiNotice(aiJob.error,true);if(['ready','applied'].includes(aiJob.status)){$('aiProposalScope').disabled=false;$('aiSummary').textContent=aiJob.summary+'\n'+aiJob.added+' new clips · '+aiJob.removed+' replaced'+(aiJob.based_on_draft?' · includes earlier draft changes':'');$('aiConversation').replaceChildren();for(const turn of aiJob.conversation||[]){for(const line of ['You: '+turn.instruction,'Director: '+turn.summary]){const p=document.createElement('p');p.textContent=line;$('aiConversation').append(p);}}$('aiClips').replaceChildren();const tr=aiJob.project.tracks.find(t=>t.id===aiJob.track);for(const c of tr.clips.filter(c=>c.origin==='ai'&&c.start<aiJob.range[1]&&c.end>aiJob.range[0])){const b=document.createElement('button');b.textContent=format(c.start)+' – '+format(c.end)+' · '+c.name;b.onclick=()=>{if(tid===aiJob.track){seek(c.start);setTimeSelection([c.start,c.end]);}};$('aiClips').append(b);}}}
async function pollAI(){if(!aiJob||!aiBusy||aiPollBusy||aiMutating)return;aiPollBusy=true;const epoch=aiEpoch;try{const next=await request('ai/job?id='+encodeURIComponent(aiJob.id));if(epoch!==aiEpoch)return;aiJob=next;renderAIJob();aiButtons();drawTimeline();preview();}catch(e){aiNotice(e.message,true);}finally{aiPollBusy=false;}}
setInterval(pollAI,1000);
new ResizeObserver(drawAI).observe($('aiCanvas'));
const aiEntry=document.createElement('button');aiEntry.id='openAI';aiEntry.className='primary ai-entry';aiEntry.textContent='✦ AI director';aiEntry.onclick=()=>openAI();$('library').append(aiEntry);
const layoutEntry=document.createElement('a');layoutEntry.href='/rig-layout';layoutEntry.target='_blank';layoutEntry.rel='noopener';layoutEntry.id='openLayout';layoutEntry.className='ai-entry';layoutEntry.textContent='Physical rig layout';$('library').append(layoutEntry);
'''
