"""Standalone physical rig editor and shared physical-map drawing functions."""

MAP_SCRIPT = r'''function physicalPoint(f,x,y){const a=f.rotation*Math.PI/180;return [f.x+x*f.width*Math.cos(a)-y*f.height*Math.sin(a),f.y+x*f.width*Math.sin(a)+y*f.height*Math.cos(a)];}
function ledPoint(g,f,i){let x,y;if(g.kind==='ring'){const a=((g.angle?.[i]??i/g.n)*(f.reverse?-1:1))*Math.PI*2;x=Math.cos(a)*.42;y=Math.sin(a)*.42;}else{const index=f.reverse?g.n-1-i:i,m=g.matrix||[];let cell=null;for(let r=0;r<m.length;r++){const c=m[r].indexOf(index);if(c>=0){cell=[c,r];break;}}if(cell){x=(cell[0]+.5)/Math.max(...m.map(row=>row.length))-.5;y=(cell[1]+.5)/m.length-.5;}else{x=g.n>1?index/(g.n-1)-.5:0;y=0;}}return physicalPoint(f,x,y);}

function drawPhysical(id,layout,colours,selected=null){const [ctx,w,h]=canvas(id);ctx.fillStyle='#111711';ctx.fillRect(0,0,w,h);ctx.font='11px system-ui';for(const [name,f] of Object.entries(layout)){const g=geom[name];if(!g)continue;ctx.strokeStyle=name===selected?'#d4ee87':'#3b4d38';ctx.beginPath();for(const [j,p] of [[-.5,-.5],[.5,-.5],[.5,.5],[-.5,.5]].entries()){const [x,y]=physicalPoint(f,...p);if(j===0)ctx.moveTo(x*w,y*h);else ctx.lineTo(x*w,y*h);}ctx.closePath();ctx.stroke();for(let i=0;i<g.n;i++){const [x,y]=ledPoint(g,f,i),rgb=colours[name]?.[i];ctx.beginPath();ctx.arc(x*w,y*h,Math.max(2,Math.min(5,f.width*w/Math.max(12,g.n)*.6)),0,2*Math.PI);ctx.fillStyle=rgb?`rgb(${rgb.join(',')})`:i===0?'#efb17b':'#7d9568';ctx.fill();if(id==='layoutCanvas'&&g.n<=24){ctx.fillStyle='#c7d2c1';ctx.fillText(String(i),x*w+5,y*h+3);}}ctx.fillStyle=name===selected?'#d4ee87':'#c7d2c1';ctx.fillText(f.label+(f.group?' · '+f.group:''),Math.max(3,Math.min(w-90,f.x*w-f.width*w/2)),Math.max(12,f.y*h-f.height*h/2-6));}}
'''

PAGE = r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rigby · Rig layout</title><link rel="icon" href="data:,"><style>
:root{color-scheme:dark;--bg:#111611;--panel:#191f19;--text:#dfe6d9;--muted:#a0ac98;--line:#354130;--accent:#d4ee87}*{box-sizing:border-box}html,body{height:100%;margin:0;overflow:hidden}body{background:var(--bg);color:var(--text);font:14px system-ui,sans-serif}button,input,select{font:inherit;color:inherit;background:#232b21;border:1px solid var(--line);border-radius:4px;padding:6px;min-width:0}button{cursor:pointer}button:hover,a:hover{border-color:var(--accent)}button:disabled{opacity:.45;cursor:default}.primary{background:var(--accent);color:#16200d}a{color:var(--accent);text-decoration:none;border:1px solid var(--line);padding:5px 8px;border-radius:4px}main{height:100vh;height:100dvh;display:flex;flex-direction:column}.dialog-bar{display:flex;align-items:center;gap:8px;padding:8px 12px;border-bottom:1px solid var(--line)}h2{font-size:16px;margin:0;flex:1}.dialog-body{display:grid;grid-template-columns:280px minmax(0,1fr);flex:1;min-height:0}.dialog-controls{background:var(--panel);padding:12px;overflow:auto;border-right:1px solid var(--line)}label{display:block;font-size:12px;color:var(--muted);margin:10px 0}label input:not([type=checkbox]),label select{display:block;width:100%;margin-top:4px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:8px}.pair label{margin:0}.row{display:flex;gap:6px;flex-wrap:wrap;margin:10px 0}.hint{font-size:12px;line-height:1.5;color:var(--muted)}.dialog-preview{display:flex;flex-direction:column;min-width:0;min-height:0}.dialog-preview .hint{margin:0;padding:6px 10px;border-top:1px solid var(--line)}#layoutCanvas{display:block;flex:1;width:100%;height:0;min-height:0;touch-action:none;cursor:grab;background:#111711}#layoutCanvas:active{cursor:grabbing}#layoutNotice{color:var(--accent);min-height:18px}#layoutSelection{min-height:30px}@media(max-width:650px){.dialog-body{grid-template-columns:200px minmax(0,1fr)}.dialog-controls{padding:8px}.dialog-bar{flex-wrap:wrap}.dialog-bar h2{font-size:14px}.dialog-preview .hint{font-size:10px}}
</style><main id="layoutDialog"><div class="dialog-bar"><h2>Physical rig layout</h2><a href="/">Live desk</a><a href="/orchestrator">Orchestrator</a></div><div class="dialog-body"><div class="dialog-controls"><p class="hint">Arrange devices as you see them from your listening position. Drag a device or enter coordinates. X runs left → right; Y runs top → bottom.</p><label>Device<select id="layoutDevice"></select></label><div class="row"><button id="identifyLayout">Identify device</button><button id="identifyLayoutLED">Identify LED 0</button></div><label>Name<input id="layoutLabel" maxlength="100"></label><label>Group<input id="layoutGroup" maxlength="100" placeholder="Top fans, behind monitor…"></label><div class="pair"><label>X<input id="layoutX" type="number" required min="0" max="1" step=".001"></label><label>Y<input id="layoutY" type="number" required min="0" max="1" step=".001"></label><label>Width<input id="layoutWidth" type="number" required min=".03" max=".8" step=".01"></label><label>Height<input id="layoutHeight" type="number" required min=".03" max=".8" step=".01"></label></div><label>Rotation clockwise °<input id="layoutRotation" type="number" required min="-360" max="360" step="1"></label><label><input id="layoutReverse" type="checkbox"> Reverse LED direction</label><div class="row"><button id="saveLayout" class="primary">Save layout</button><button id="resetLayout">Reset positions</button></div><p id="layoutNotice" class="hint" role="status"></p></div><div class="dialog-preview"><canvas id="layoutCanvas" class="rig-map" aria-label="Drag devices to place them in physical space"></canvas><p class="hint">Labels use your chosen names; dots show LED indices in physical order. LED 0 is highlighted. This map guides the AI; it does not change your hardware patch.</p><p id="layoutSelection" class="hint"></p></div></div></main><script>
'use strict';
const $=id=>document.getElementById(id),clone=value=>structuredClone(value);
let geom={},layoutConfig=null,layoutDraft={},layoutSelected=null,layoutDragging=null,layoutDirty=false;
function message(value){$('layoutNotice').textContent=value;}
async function request(path,body){const r=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||r.statusText);return data;}
function canvas(id){const el=$(id),dpr=window.devicePixelRatio||1,w=el.clientWidth,h=el.clientHeight;el.width=Math.round(w*dpr);el.height=Math.round(h*dpr);const ctx=el.getContext('2d');ctx.scale(dpr,dpr);return [ctx,w,h];}
''' + MAP_SCRIPT + r'''function layoutFields(){const f=layoutDraft[layoutSelected];if(!f)return;for(const [id,key] of [['Label','label'],['Group','group'],['X','x'],['Y','y'],['Width','width'],['Height','height'],['Rotation','rotation']])$('layout'+id).value=f[key];$('layoutReverse').checked=f.reverse;$('layoutDevice').value=layoutSelected;drawPhysical('layoutCanvas',layoutDraft,{},layoutSelected);$('layoutSelection').textContent=layoutSelected+' · '+geom[layoutSelected].n+' LEDs';}
async function openLayout(){try{layoutConfig=await request('rig-layout');$('identifyLayout').disabled=$('identifyLayoutLED').disabled=!layoutConfig.can_identify;layoutDraft=clone(layoutConfig.layout);layoutSelected=Object.keys(layoutDraft)[0];if(!layoutSelected){message('No devices in the current patch. Connect devices in the live desk first.');return;}$('layoutDevice').replaceChildren(...Object.keys(layoutDraft).map(name=>{const o=document.createElement('option');o.value=name;o.textContent=name;return o;}));$('layoutNotice').textContent=layoutConfig.error||'Changes are saved only when you choose Save layout.';layoutFields();}catch(e){message(e.message,true);}}
for(const [id,led] of [['identifyLayout',null],['identifyLayoutLED',0]])$(id).onclick=async()=>{try{await request('rig-layout/identify',{fixture:layoutSelected,led});$('layoutNotice').textContent='Identifying '+layoutSelected+(led===null?'':' LED '+led)+' on the real LEDs for 3 seconds';}catch(e){$('layoutNotice').textContent=e.message;}};
$('layoutDevice').onchange=()=>{layoutSelected=$('layoutDevice').value;layoutFields();};
for(const [id,key] of [['Label','label'],['Group','group'],['X','x'],['Y','y'],['Width','width'],['Height','height'],['Rotation','rotation'],['Reverse','reverse']])$('layout'+id).oninput=()=>{if(!layoutSelected)return;const input=$('layout'+id);if(input.type==='number'&&!input.checkValidity())return;layoutDraft[layoutSelected][key]=input.type==='checkbox'?input.checked:input.type==='number'?+input.value:input.value;drawPhysical('layoutCanvas',layoutDraft,{},layoutSelected);layoutDirty=true;$('layoutNotice').textContent='Unsaved layout changes';};
$('layoutCanvas').onpointerdown=e=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;const found=Object.entries(layoutDraft).reverse().find(([name,f])=>{const a=-f.rotation*Math.PI/180,dx=x-f.x,dy=y-f.y;return Math.abs(dx*Math.cos(a)-dy*Math.sin(a))<=f.width/2+.02&&Math.abs(dx*Math.sin(a)+dy*Math.cos(a))<=f.height/2+.02;});if(!found)return;layoutSelected=found[0];layoutDragging={dx:x-found[1].x,dy:y-found[1].y};e.currentTarget.setPointerCapture(e.pointerId);layoutFields();};
$('layoutCanvas').onpointermove=e=>{if(!layoutDragging)return;const r=e.currentTarget.getBoundingClientRect(),f=layoutDraft[layoutSelected];f.x=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width-layoutDragging.dx));f.y=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height-layoutDragging.dy));f.x=Math.round(f.x*1000)/1000;f.y=Math.round(f.y*1000)/1000;layoutFields();layoutDirty=true;$('layoutNotice').textContent='Unsaved layout changes';};$('layoutCanvas').onpointerup=$('layoutCanvas').onpointercancel=()=>{layoutDragging=null;};
$('resetLayout').onclick=()=>{for(const [name,g] of Object.entries(geom)){layoutDraft[name]={label:name,group:'',x:g.origin[0],y:1-g.origin[1],width:.15,height:.15,rotation:0,reverse:false};}layoutDirty=true;layoutFields();$('layoutNotice').textContent='Reset draft — save to keep these positions.';};
$('saveLayout').onclick=async()=>{try{for(const input of document.querySelectorAll('input[type=number]'))if(!input.reportValidity())throw Error('Check the highlighted layout value');layoutConfig=await request('rig-layout',{layout:layoutDraft,revision:layoutConfig.revision});layoutDirty=false;$('layoutNotice').textContent='Physical layout saved';}catch(e){$('layoutNotice').textContent=e.message;}};

new ResizeObserver(()=>drawPhysical('layoutCanvas',layoutDraft,{},layoutSelected)).observe($('layoutCanvas'));
window.addEventListener('beforeunload',e=>{if(layoutDirty){e.preventDefault();e.returnValue='';}});
(async()=>{try{geom=await request('rig-layout/geometry');await openLayout();}catch(e){message(e.message);}})();
</script></html>'''
